modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Lileep/${modName}/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
# logoFile="logo.png"
credits="Thanks for developers"
authors="Lileep"
description='''
A navigator displaying mod for Pixelmon Virtual Battle NPC
'''

[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modId}]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.9,)"
    ordering="NONE"
    side="BOTH"
